### ISSUE TITLE
Converting Borb PDF to base64 without saving

### ISSUE THREAD

**Issue by autsauce** [jorisschellekens/borb#68] opened 2022-01-30 18:24 UTC
I am working with an API that requires me to upload PDF documents encoded as base64. Is there a way to convert the borb.pdf.document.Document object to bytes without saving it first? 

Here is how I am currently handling it:

```
  with open('mydocument.pdf', 'wb') as pdf_file_handle:
   PDF.dumps(pdf_file_handle, pdf)

  with open('mydocument.pdf', 'rb') as pdf_file_handle:
   encoded_string = base64.b64encode(pdf_file_handle.read())
```

Ideally, I would like to go straight from the pdf to the endcoded_string to avoid having to manage all the saved documents.

**Comment by jorisschellekens** [comment] 2022-01-30 18:33
Hi there,

Please check the existing (closed) issues before creating a new one.

Your question is a duplicate of issue #58 and issue #54 

Kind regards,
Joris Schellekens

**Closed by jorisschellekens** 2022-01-30 18:33 UTC
